name: Notify Slack on PR Open

on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  notify_slack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get Slack mentions
        id: get_mentions
        run: |
          # Parse the JSON mapping stored in the secret
          MAPPING='${{ secrets.SLACK_ID_MAPPING }}'

          # Get the PR author's Slack ID
          AUTHOR_SLACK_ID=$(echo $MAPPING | jq -r --arg AUTHOR "${{ github.event.pull_request.user.login }}" '.[$AUTHOR] // empty')

          # Set author mention if found
          if [ ! -z "$AUTHOR_SLACK_ID" ]; then
            echo "author_mention=<@$AUTHOR_SLACK_ID>" >> $GITHUB_OUTPUT
          else
            echo "author_mention=${{ github.event.pull_request.user.login }}" >> $GITHUB_OUTPUT
          fi

          # Initialize reviewer mentions string
          REVIEWER_MENTIONS=""

          # Get requested reviewers' Slack IDs
          for REVIEWER in $(echo '${{ toJson(github.event.pull_request.requested_reviewers) }}' | jq -r '.[].login'); do
            REVIEWER_SLACK_ID=$(echo $MAPPING | jq -r --arg REVIEWER "$REVIEWER" '.[$REVIEWER] // empty')
            if [ ! -z "$REVIEWER_SLACK_ID" ]; then
              REVIEWER_MENTIONS="$REVIEWER_MENTIONS <@$REVIEWER_SLACK_ID>"
            else
              REVIEWER_MENTIONS="$REVIEWER_MENTIONS $REVIEWER"
            fi
          done

          # Set reviewer mentions output
          echo "reviewer_mentions=$REVIEWER_MENTIONS" >> $GITHUB_OUTPUT

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: '#ito-frontend'
          SLACK_ICON: https://github.com/github.png?size=48
          SLACK_MESSAGE: |
            有新的 PR 喔! :rocket:
            *PR 名稱:* ${{ github.event.pull_request.title }} from ${{ steps.get_mentions.outputs.author_mention }}
            *Reviewers:* ${{ steps.get_mentions.outputs.reviewer_mentions }}
            請 協助 Code Review，愛您哦 :heart:
          SLACK_TITLE: PR # ${{ github.event.pull_request.number }}: ${{ github.event.pull_request.title }}
          SLACK_USERNAME: GitHub
          SLACK_FOOTER: '<${{ github.event.pull_request.html_url }}|View PR>'
