name: NPM Package Release Notification

on:
  release:
    types: [published]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get package info
        id: package
        run: |
          PACKAGE_NAME=$(node -p "require('./package.json').name")
          echo "name=$PACKAGE_NAME" >> $GITHUB_OUTPUT

      - name: Check if patch release
        id: check-patch
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          if [[ $VERSION =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "is_patch=true" >> $GITHUB_OUTPUT
          else
            echo "is_patch=false" >> $GITHUB_OUTPUT
          fi

      - name: Send Slack notification
        if: steps.check-patch.outputs.is_patch == 'true'
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: '#ito-frontend'
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_MESSAGE: |
            *${{ steps.package.outputs.name }}* has been updated! 🚀

            NPM URL: https://www.npmjs.com/package/${{ steps.package.outputs.name }}
            GitHub Release: ${{ github.event.release.html_url }}
          SLACK_TITLE: ${{ steps.package.outputs.name }} updated!
          SLACK_USERNAME: GitHub Actions
