name: NPM Package Release Notification

on:
  release:
    types: [published]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Check if patch release
        id: check-patch
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          if [[ $VERSION =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "is_patch=true" >> $GITHUB_OUTPUT
          else
            echo "is_patch=true" >> $GITHUB_OUTPUT
          fi

      - name: Send Slack notification
        if: steps.check-patch.outputs.is_patch == 'true'
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: '#ito-frontend'
          SLACK_COLOR: '#36a64f'
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_MESSAGE: 'A new patch version of the package has been released: ${{ github.ref }}'
          SLACK_TITLE: '[Alert] New Package Release'
          SLACK_USERNAME: GitHub Actions
